spring.application.name=base-java-spring-be
spring.datasource.url=jdbc:postgresql://localhost:5432/mp3-to-audio
spring.datasource.username=postgres
spring.datasource.password=quoctinh
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
seeder.enabled=false
spring.security.user.name=admin
spring.security.user.password=12345678
jwt.secret=4tMkDPfcx+2O4PIgIAvlC6LAxSFYiEd8kLbGY4YYFfcxx1EHwjQZq6b+n/KCetfAh9Wm4DeC2v6bgj4FijVdBQ==
jwt.expiration=86400000
server.port=8888
vnpay.secretKey='secretKey'
spring.web.resources.add-mappings=false
# RabbitMQ connection settings
app.ws.useRelay=true
app.ws.auto-startup=false
spring.rabbitmq.host=localhost
spring.rabbitmq.username=tinhnq
spring.rabbitmq.password=quoctinh
rabbitmq.stomp.port=61613
stomp.virtualHost=/

# WebSocket STOMP settings
app.websocket.endpoint=/ws
app.websocket.application-destination-prefix=/user
app.websocket.broker-prefixes=/topic,/queue

# JWT settings
app.jwt.secret=25TinhNQ0519041997
logging.level.org.springframework.messaging=INFO
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.messaging.simp.broker=DEBUG
logging.level.org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler=DEBUG

tts.storage-dir=data/audio
tts.provider=gcloud          
tts.voice=vi-VN-Wavenet-A
tts.speaking-rate=1.0
tts.pitch=0.0

azure.speech.key=YOUR_REAL_AZURE_SPEECH_KEY
azure.speech.region=eastasia
azure.speech.voice=vi-VN-HoaiMyNeural    # ho?c vi-VN-NamMinhNeural
azure.speech.format=audio-24khz-48kbitrate-mono-mp3

# Cache file
app.tts.storage-dir=/var/data/tts
app.tts.ffmpeg-path=C:\\ffmpeg-8.0-full_build\\bin\\ffmpeg.exe

# S?a thành 8001
app.tts.python-dubbing-url=http://localhost:8001/api/v1/dubbing
app.tts.python-whisper-url=http://localhost:8008/api/v1/dubbing/whisper
app.tts.python-tts-url=http://localhost:8008/api/v1/dubbing/tts-gen
app.tts.python-mix-url=http://localhost:8008/api/v1/dubbing/mix-video
app.tts.python-translate-url=http://localhost:8008/api/v1/dubbing/translate
